blog/urls.py
from django.urls import path
from blog.views import BlogPostListView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='home'),
]

raad/urls.py
from django.urls import path
from raad.views.authorization_views import LoginView, RegisterView, logout_view, send_otp
from raad.views.views import (
    dashboard_view, add_messenger_admin, MessengerAdminUpdateView,
    delete_messenger_admin, DeviceUpdateView)
from raad.views.api_views import (
    validate_license_key,
    get_user_companies,
    get_company_not_activated_devices,
    get_full_companies_data)

app_name = 'raad'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('send_otp/', send_otp, name='send_otp'),
    # path('signup/', RegisterView.as_view(), name='signup'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('company/<int:company_id>/add_messenger_admin/', add_messenger_admin, name='add_messenger_admin'),
    path('edit_messenger_admin/<int:pk>/', MessengerAdminUpdateView.as_view(), name='edit_messenger_admin'),
    path('delete_messenger_admin/<int:admin_id>/', delete_messenger_admin, name='delete_messenger_admin'),
    path('device/<int:pk>/', DeviceUpdateView.as_view(), name='device_update'),
    path('license/validate/', validate_license_key, name='validate_serial'),
    path('get_user_companies/', get_user_companies, name='get_user_companies'),
    path('get_company_devices/', get_company_not_activated_devices, name='get_company_not_activated_devices'),
    path('get_full_data/', get_full_companies_data, name='get_full_companies_data'),
]

raad_panel/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'رعد'
admin.site.index_title = 'رعد'
admin.site.site_title = 'رعد'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('raad.urls')),
    path('tickets/', include('ticket.urls')),
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.urls import path
from ticket.views import UserTicketListView, ticket_detail, new_ticket

app_name = 'ticket'

urlpatterns = [
    path('', UserTicketListView.as_view(), name='tickets'),
    path('<int:ticket_id>/', ticket_detail, name='ticket_detail'),
    path('new/', new_ticket, name='new_ticket'),
]

templates/base.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background-color: #f4f4f4;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .navbar {
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: #f9f9f9;
            padding: 10px 0;
            width: 100%;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .navbar a {
            color: #333;
            text-decoration: none;
            padding: 10px 20px;
            font-weight: bold;
        }

        .navbar a:hover {
            background-color: #e6e6e6;
            border-radius: 5px;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 90%;
            margin: 20px auto;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
            font-size: 2.5em;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'blog:home' %}">خانه</a>
        <a href="{% url 'raad:dashboard' %}">داشبورد</a>
        <a href="{% url 'ticket:tickets' %}">تیکت</a>
        <a href="#">درباره ما</a>
        {% if user.is_authenticated %}
        <a href="{% url 'raad:logout' %}" class="logout-button">خروج</a>
        {% else %}
        <a href="{% url 'raad:login' %}" class="login-button">ورود</a>
        {% endif %}
    </div>
    <div class="container">
        <h1>{% block content_title %}رعد{% endblock %}</h1>
        {% block content %}{% endblock %}
    </div>
</body>
</html>