blog/urls.py
from django.urls import path
from blog.views import BlogPostListView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='home'),
]

raad/urls.py
from django.urls import path
from raad.views.authorization_views import LoginView, RegisterView, logout_view, send_otp
from raad.views.views import (
    dashboard_view, add_messenger_admin, MessengerAdminUpdateView,
    delete_messenger_admin, DeviceUpdateView)
from raad.views.api_views import (
    validate_license_key,
    get_user_companies,
    get_company_not_activated_devices,
    get_full_companies_data)

app_name = 'raad'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('send_otp/', send_otp, name='send_otp'),
    # path('signup/', RegisterView.as_view(), name='signup'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('company/<int:company_id>/add_messenger_admin/', add_messenger_admin, name='add_messenger_admin'),
    path('edit_messenger_admin/<int:pk>/', MessengerAdminUpdateView.as_view(), name='edit_messenger_admin'),
    path('delete_messenger_admin/<int:admin_id>/', delete_messenger_admin, name='delete_messenger_admin'),
    path('device/<int:pk>/', DeviceUpdateView.as_view(), name='device_update'),
    path('license/validate/', validate_license_key, name='validate_serial'),
    path('get_user_companies/', get_user_companies, name='get_user_companies'),
    path('get_company_devices/', get_company_not_activated_devices, name='get_company_not_activated_devices'),
    path('get_full_data/', get_full_companies_data, name='get_full_companies_data'),
]

raad_panel/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'رعد'
admin.site.index_title = 'رعد'
admin.site.site_title = 'رعد'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('raad.urls')),
    path('tickets/', include('ticket.urls')),
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/add_messenger_admin.html
{% extends 'base.html' %}

{% block title %}افزودن مدیر پیامرسان{% endblock %}

<h1>{% block content_title %}افزودن مدیر پیامرسان به شرکت {{ company.name }}{% endblock %}</h1>

{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="{{ form.messenger.id_for_label }}" class="form-label">نوع پیامرسان</label>
            {{ form.messenger }}
        </div>
        <div class="input-group">
            <label for="{{ form.admin_messenger_id.id_for_label }}" class="form-label">شناسه پیامرسان</label>
            {{ form.admin_messenger_id }}
        </div>
        <br>
        <button type="submit" class="btn">ذخیره</button>
    </form>
</div>

<style>
    .form-label {
        color: #0e0d0d;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #333;
        border-radius: 5px;
        background-color: #333;
        color: #ffffff;
    }

    .form-control:focus {
        outline: none;
    }

    .btn {
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .btn:hover {
        background-color: #0056b3;
    }
    input {
    width: 97%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}
    select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}
</style>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% load jalali_tags %}

{% block title %}داشبورد{% endblock %}


<h1>{% block content_title %}داشبورد{% endblock %}</h1>

{% block content %}
<h1> {{ user.username }} خوش آمدید</h1>

<div class="container">

    <div class="company-list">
        {% for company in companies %}
            <div class="company-row">
                <div class="company-header">
                    <span>{{ company.name }}</span>
                    <span class="company-expiration">تاریخ انقضا: {{ company.expiration_date|to_jalali:'%y/%m/%d' }}</span>
                    <i class="fas fa-chevron-down"></i>
                </div>
                <div class="company-details">
                    <input type="text" name="{{ company.license_key }}" value="{{ company.license_key }}" class="form-control readonly-license-key" id="license-{{ company.id }}">
                    <br>
                    <br>
                    <div class="details-content">
                        <h3 style="color: black;">دستگاه‌ها:</h3>
                        <ul>
                            {% for device in company.devices.all %}
                                <li>
                                    <span class="admin-details" style="font-size: 25px;">
                                         <a href="{% url 'raad:device_update' device.id %}" class="update-button">
                                             {{ device.name }}
                                         </a>
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                        <h3 style="color: black;">مدیران پیامرسان:</h3>
                        <ul>
                            {% for admin in company.admins.all %}
                                <li class="admin-item">
                                    <span class="admin-details" style="font-size: 25px;">
                                        <a href="{% url 'raad:edit_messenger_admin' admin.id %}" class="edit-admin-link">
                                         {{ admin.messenger }} : {{ admin.admin_messenger_id }}
                                        </a>
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'raad:add_messenger_admin' company_id=company.id %}">
                                <button type="button" class="btn btn-danger" style="width: max-content">افزودن مدیر پیامرسان</button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<style>
    .container {
        text-align: center;
    }

    .company-list {
        font-family: Arial, sans-serif;
    }

    .company-row {
        margin: 10px;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        cursor: pointer;
    }

    .company-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #f7f7f7;
        padding: 10px;
        border-radius: 5px;
    }

    .company-header span {
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }

    .company-header .company-expiration {
        font-size: 14px;
        color: #888;
    }

    .company-header i {
        font-size: 20px;
        color: #333;
        transition: transform 0.3s;
    }

    .company-details {
        display: none;
        margin-top: 10px;
    }

    .details-content {
        background-color: #f7f7f7;
        padding: 10px;
        border-radius: 5px;
    }

    .company-details h3 {
        font-size: 16px;
        font-weight: bold;
        color: #007BFF;
    }

    .company-details ul {
        list-style-type: none;
        padding: 0;
    }

    .company-details ul li {
        margin-bottom: 5px;
        font-size: 14px;
        color: #555;
        display: flex;
        align-items: center;
    }

    .company-details ul li a {
        margin-left: 10px;
        color: #007BFF;
        text-decoration: none;
    }

    .add-admin-btn {
        background-color: #007BFF;
        color: #fff;
        border: none;
        padding: 5px 10px;
        border-radius: 5px;
        cursor: pointer;
        margin-top: 10px;
    }

    .add-admin-btn:hover {
        background-color: #0056b3;
    }

    .company-row.opened .company-header i {
        transform: rotate(180deg);
    }

    /* Style for admin item list */
.admin-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 0;
    border-bottom: 1px solid #ccc;
    list-style: none;
}

/* Style for admin details */
.admin-details {
    flex-grow: 1; /* Expands to take available space */
    color: #333; /* Text color for details */
}

.admin-actions {
    margin-left: 10px;
    font-size: 14px;
}

.edit-admin-link,
.delete-admin-link {
    color: #007BFF; /* Link color */
    text-decoration: none;
    margin-left: 10px;
}

/* Hover effect for links */
.edit-admin-link:hover,
.delete-admin-link:hover {
    text-decoration: underline; /* Underline on hover */
}
/* Style for readonly license key input */
.readonly-license-key {
    width: 97%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}
    .btn {
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        width: 20%;
    }

    .btn:hover {
        background-color: #0056b3;
    }

</style>
<script>
    // Add click event listeners to toggle company details
    const companyRows = document.querySelectorAll('.company-row');
    companyRows.forEach(row => {
        const header = row.querySelector('.company-header');
        const details = row.querySelector('.company-details');
        header.addEventListener('click', () => {
            row.classList.toggle('opened');
            details.style.display = details.style.display === 'none' ? 'block' : 'none';
        });
        row.addEventListener('click', (event) => {
            const licenseInput = event.target.closest('.company-row').querySelector('.readonly-license-key');
            if (event.target.classList.contains('readonly-license-key')) {
                const el = document.createElement('textarea');
                el.value = licenseInput.value;
                document.body.appendChild(el);
                el.select();
                document.execCommand('copy');
                document.body.removeChild(el);
            }
        });
    });

</script>
{% endblock %}

templates/dashboard/delete_messenger_admin.html
{% extends 'base.html' %}

{% block title %}حذف مدیر پیامرسان{% endblock %}

<h1>{% block content_title %}حذف مدیر پیامرسان{% endblock %}</h1>

{% block content %}

<div class="container">
    <h2 style="color: white;">آیا از حذف مدیر پیامرسان "{{ object.admin_messenger_id }}" مطمئن هستید؟</h2>

    <p style="color: white;"><strong style="color: white;">پیامرسان:</strong> {{ object.messenger }}</p>
    <p style="color: white;"><strong style="color: white;">شناسه مدیر پیامرسان:</strong> {{ object.admin_messenger_id }}</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">حذف</button>
        <br><br>
        <a href="{% url 'raad:dashboard' %}" class="btn btn-secondary">بازگشت</a>
    </form>
</div>

<style>
    .form-label {
        color: #ffffff;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #333;
        border-radius: 5px;
        background-color: #333;
        color: #ffffff;
    }

    .form-control:focus {
        outline: none;
    }

    .btn {
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .btn:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}

templates/dashboard/device.html
{% extends 'base.html' %}

{% block title %}ویرایش نام دستگاه{% endblock %}

{% block content_title %}
<h1>شرکت  {{ company_name }}</h1>
<h1>ویرایش نام دستگاه {{ device_model.name }}</h1>
{% endblock %}

{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="{{ form.name.id_for_label }}" class="form-label">نام دستگاه</label>
            {{ form.name }}
        </div>
        <br>
        <button type="submit" class="btn">ذخیره</button>
    </form>
</div>

<style>
    .form-label {
        color: #131111;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #333;
        border-radius: 5px;
        background-color: #333;
        color: #ffffff;
    }

    .form-control:focus {
        outline: none;
    }

    .btn {
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .btn:hover {
        background-color: #0056b3;
    }
    input {
    width: 97%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}
</style>
{% endblock %}

templates/dashboard/update_messenger_admin.html
{% extends 'base.html' %}

{% block title %} مدیر پیامرسان{% endblock %}

<h1>{% block content_title %} مدیر پیامرسان {{ company.name }}{% endblock %}</h1>

{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="{{ form.messenger.id_for_label }}" class="form-label">نوع پیامرسان</label>
            {{ form.messenger }}
        </div>
        <div class="input-group">
            <label for="{{ form.admin_messenger_id.id_for_label }}" class="form-label">شناسه پیامرسان</label>
            {{ form.admin_messenger_id }}
        </div>
        <br>
        <button type="submit" class="btn">ذخیره</button>
    </form>
    <br>
    <button type="button" class="btn btn-danger" id="deleteButton">
        حذف
    </button>
    <br><br>
<!--    <a href="{% url 'raad:dashboard' %}" class="btn btn-secondary">بازگشت</a>-->
</div>

<script>
    // Add confirmation dialog before redirecting to delete URL
    document.getElementById('deleteButton').addEventListener('click', function () {
        if (window.confirm('آیا از حذف مدیر پیامرسان مطمئن هستید؟')) {
            window.location.href = "{% url 'raad:delete_messenger_admin' object_id %}";
        }
    });
</script>

<style>
    .form-label {
        color: #ffffff;
        display: block;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #333;
        border-radius: 5px;
        background-color: #333;
        color: #ffffff;
    }

    .form-control:focus {
        outline: none;
    }

    .btn {
        background-color: #007BFF;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        width: 100%;
    }

    .btn:hover {
        background-color: #0056b3;
    }
        input {
    width: 97%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}
    select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f7f7f7;
    color: #333;
    font-size: 16px; /* Adjust the font size as needed */
    font-weight: bold;
    cursor: default;
    outline: none;
}

</style>
{% endblock %}